model_path: "CodeLLM/Qwen2.5-Coder-0.5B-Instruct"
eval_dataset_name: "repobench"
dp_size: 1
tp_size: 1
dp_master_ip: "127.0.0.1"
dp_master_port: 6530 #29310
data_path_dir: "datasets/repobench/java/test"
debug_mode: false
language: "java"
max_input_tokens: 512
save_file_path: "output_dir/generation/repobench/java/QwenCoder0.5B.json"
#system_prompt: " You first think about the reasoning process as an internal monologue and then provide the user with the answer. Respond in the following format: <think>\n...\n</think>\n<answer>\n...\n</answer>"
system_prompt: "You are a helpful assistant tasked with completing the next line of a repository-level code file.  You are provided with an incomplete code file, and other code snippets from the same repository are provided as comments above the code.  You should provide the user with the next line of the incomplete code. Please respond in the following format: <answer>\n```...```\n</answer>"
temperature: 0.7
top_p: 1.0
gpu_memory_utilization: 0.25
dtype: "float16"
use_lora: false
lora_path: "None"
without_context: false
     