# Model arguments
model_name_or_path: /data/dzl/package/CodeLLM/Qwen2.5-Coder-7B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2
use_peft: true

# Data training arguments
language: python
prompt_mode: split # prompt_mode: comment
dataset_name: /data/dzl/RL_project/RepoCompletion/datasets/repobench/python
dataset_prompt_column: prompt
dataset_completion_column: solution
system_prompt: "You are a helpful assistant tasked with completing the next line of a repository-level code file.
 You are provided with an incomplete code file and other code snippets from the same repository. 
 You first think about the reasoning process as an internal monologue and then provide the user with the next line of the incomplete code.
 The reasoning process should be enclosed within <think> and </think> tags, while the final answer should be enclosed within <answer> and </answer> tags. 
 Please respond in the following format: <think>\n...\n</think>\n<answer>\n```...```\n</answer>"

# system_prompt: "You first think about the reasoning process as an internal monologue and then provide the user with the answer. 
#  Respond in the following format: <think>\n...\n</think>\n<answer>\n...\n</answer>"

# GRPO trainer config
beta: 0.001
bf16: true
do_eval: false
eval_strategy: "no"
use_vllm: true
vllm_gpu_memory_utilization: 0.7
vllm_server_port: 8100
group_port: 56216
do_eval: false
gradient_accumulation_steps: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: Qwen2.5-7B-Instruct-GRPO
hub_strategy: every_save
learning_rate: 1.0e-04
log_completions: true
log_level: info
logging_first_step: true
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: constant_with_warmup
max_grad_norm: 0.2
max_prompt_length: 3000
max_completion_length: 2048
max_steps: -1
num_generations: 6
num_train_epochs: 1
output_dir: weights/python/Qwen2.5-7B-Instruct-ablation-intent
overwrite_output_dir: true
per_device_train_batch_size: 12
push_to_hub: false
wandb_project: R1
report_to:
- wandb
reward_funcs: #thought_length_by_CodeID
- codelines_reward
- code_similarity
- code_format
reward_weights:
- 0.1
- 1.0
- 0.2
save_strategy: "steps"
save_steps: 0.2
eval_steps: 0.2
save_total_limit: 50
seed: 42
temperature: 0.7
warmup_ratio: 0.1
model_init_kwargs:
  torch_load_kwargs:
    weights_only: false
